/* ═══════════════════════════════════════════════════════════════
   FITCORE — DATA.JS
   All exercise, diet, and supplement data.
   Exercise GIFs: muscles.wiki CDN (public, no auth required)
═══════════════════════════════════════════════════════════════ */

// ── EXERCISE GIF MAP (muscles.wiki public CDN) ──────────────────
const GIF = {
  bench:        "https://muscles.wiki/gif/barbell-bench-press.gif",
  incline_db:   "https://muscles.wiki/gif/dumbbell-incline-bench-press.gif",
  cable_fly:    "https://muscles.wiki/gif/cable-fly-crossovers.gif",
  ohp:          "https://muscles.wiki/gif/barbell-shoulder-press.gif",
  lat_raise:    "https://muscles.wiki/gif/dumbbell-lateral-raise.gif",
  dip:          "https://muscles.wiki/gif/chest-dip.gif",
  tri_pushdown: "https://muscles.wiki/gif/triceps-pushdown.gif",
  pullup:       "https://muscles.wiki/gif/pull-up.gif",
  barbell_row:  "https://muscles.wiki/gif/bent-over-barbell-row.gif",
  lat_pulldown: "https://muscles.wiki/gif/lat-pulldown.gif",
  cable_row:    "https://muscles.wiki/gif/seated-cable-row.gif",
  ez_curl:      "https://muscles.wiki/gif/barbell-curl.gif",
  hammer_curl:  "https://muscles.wiki/gif/dumbbell-hammer-curl.gif",
  face_pull:    "https://muscles.wiki/gif/face-pull.gif",
  arnold_press: "https://muscles.wiki/gif/arnold-press.gif",
  db_press:     "https://muscles.wiki/gif/dumbbell-shoulder-press.gif",
  rear_fly:     "https://muscles.wiki/gif/reverse-fly.gif",
  upright_row:  "https://muscles.wiki/gif/barbell-upright-row.gif",
  skullcrusher: "https://muscles.wiki/gif/ez-bar-skullcrusher.gif",
  deadlift:     "https://muscles.wiki/gif/deadlift.gif",
  db_row:       "https://muscles.wiki/gif/dumbbell-bent-over-row.gif",
  shrug:        "https://muscles.wiki/gif/dumbbell-shrug.gif",
  conc_curl:    "https://muscles.wiki/gif/concentration-curls.gif",
  hyperext:     "https://muscles.wiki/gif/back-extension.gif",
  plank:        "https://muscles.wiki/gif/plank.gif",
  cable_crunch: "https://muscles.wiki/gif/cable-crunch.gif",
  leg_raise:    "https://muscles.wiki/gif/hanging-leg-raise.gif",
  ab_wheel:     "https://muscles.wiki/gif/ab-wheel-rollout.gif",
  russian:      "https://muscles.wiki/gif/russian-twist.gif",
  side_plank:   "https://muscles.wiki/gif/side-plank.gif",
};

// ── WORKOUT TYPES ───────────────────────────────────────────────
const WORKOUT_TYPES = [
  {
    id: "pecho", name: "Pecho", icon: "💪",
    color: "#ff6b35", label: "PUSH",
    sub: "Pectorales · Deltoides anterior · Tríceps",
    exercises: [
      {
        name: "Press de banca plano",
        muscle: "Pectoral mayor — porción esternal",
        equipment: "Banco plano + barra olímpica",
        gif: GIF.bench,
        weight: "20–30 kg total",
        sets: "4×6-8", rest: "3 min",
        howto: "Túmbate en el banco con arco lumbar natural. Agarre algo más ancho que los hombros. Baja la barra controlando 2-3 segundos hasta rozar el pecho, empuja explosivamente. Los codos van a ~70° del torso, nunca perpendiculares.",
        pro: "Retrae las escápulas antes de bajar la barra — esto protege el hombro y mejora la palanca.",
      },
      {
        name: "Press inclinado con mancuernas",
        muscle: "Pectoral mayor — porción clavicular (zona alta)",
        equipment: "Banco inclinado 30-45° + mancuernas",
        gif: GIF.incline_db,
        weight: "8–12 kg c/mano",
        sets: "3×8-10", rest: "2 min",
        howto: "Banco a 30-45°. Mancuernas al nivel del pecho, codos a ~75°. Sube hasta casi unir las mancuernas sin tocarlas. Bajada lenta en 3 segundos.",
        pro: "A más inclinación, más zona alta del pecho. No pases de 45° o empiezan los hombros a dominar.",
      },
      {
        name: "Aperturas en polea cruzada",
        muscle: "Pectoral mayor — fibras medias e inferiores",
        equipment: "Cable crossover — poleas altas",
        gif: GIF.cable_fly,
        weight: "5–8 kg c/lado",
        sets: "3×12-15", rest: "90s",
        howto: "De pie en el centro, poleas en alto. Lleva los brazos hacia abajo y al centro con ligera flexión de codo fija. Contrae el pecho 1s al unir las manos. Control total al soltar.",
        pro: "El cable mantiene tensión constante. Las mancuernas no tienen tensión al final — por eso el cable es superior para las aperturas.",
      },
      {
        name: "Press militar con barra",
        muscle: "Deltoides anterior + trapecio + tríceps",
        equipment: "Barra olímpica — rack o suelo",
        gif: GIF.ohp,
        weight: "20–25 kg total",
        sets: "4×6-8", rest: "3 min",
        howto: "De pie, agarre ligeramente más ancho que hombros, barra a la clavícula. Core muy activo. Empuja la barra verticalmente, mete la cabeza cuando la barra pase. No arquear la lumbar.",
        pro: "Aprieta el glúteo al máximo — evita la hiperextensión lumbar y transfiere más fuerza al press.",
      },
      {
        name: "Elevaciones laterales",
        muscle: "Deltoides medial — cabeza lateral",
        equipment: "Mancuernas de pie o sentado",
        gif: GIF.lat_raise,
        weight: "4–6 kg c/mano",
        sets: "3×12-15", rest: "90s",
        howto: "Sube los brazos lateralmente hasta la altura de los hombros. Codos ligeramente flexionados, muñecas neutras. 2s subida / 2s bajada. Sin balanceo del torso.",
        pro: "Inclina el pulgar ligeramente hacia abajo al llegar arriba — activa más la cabeza media del deltoides.",
      },
      {
        name: "Fondos en paralelas",
        muscle: "Pectoral inferior + tríceps + deltoides anterior",
        equipment: "Barras paralelas del gimnasio",
        gif: GIF.dip,
        weight: "Peso corporal → disco cuando hagas 12+ reps",
        sets: "3×10-12", rest: "2 min",
        howto: "Cuerpo inclinado hacia adelante para activar más el pecho. Baja hasta que los hombros lleguen al nivel de los codos. Empuja sin bloquear las rodillas.",
        pro: "A más inclinación del torso = más pecho. Cuerpo erguido = más tríceps. Elige según el objetivo del día.",
      },
      {
        name: "Extensión tríceps en polea alta",
        muscle: "Tríceps braquial — las 3 cabezas",
        equipment: "Polea alta con cuerda",
        gif: GIF.tri_pushdown,
        weight: "10–15 kg",
        sets: "3×12-15", rest: "90s",
        howto: "Codos pegados al torso y fijos como bisagra. Empuja la cuerda hacia abajo hasta extensión completa, separando los extremos al final. Sube lento sin que los codos se levanten.",
        pro: "Separar los extremos de la cuerda al final genera máxima contracción del tríceps. No lo saltes.",
      },
    ]
  },
  {
    id: "espalda", name: "Espalda A", icon: "🦅",
    color: "#4ecdc4", label: "PULL",
    sub: "Dorsal ancho · Romboides · Bíceps",
    exercises: [
      {
        name: "Dominadas",
        muscle: "Dorsal ancho + bíceps + redondo mayor",
        equipment: "Barra de dominadas (asistidas si es necesario)",
        gif: GIF.pullup,
        weight: "Peso corporal → añadir disco cuando hagas 10+ seguidas",
        sets: "4×6-8", rest: "3 min",
        howto: "Agarre prono más ancho que hombros. Inicia retrayendo las escápulas antes de doblar los codos. Sube hasta que la barbilla supere la barra. Baja lento 3-4 segundos.",
        pro: "El error más común: tirar con los brazos en vez de 'empujar la barra hacia el suelo' con los codos. Imagina eso.",
      },
      {
        name: "Remo con barra Yates",
        muscle: "Dorsal ancho + romboides + bíceps",
        equipment: "Barra olímpica",
        gif: GIF.barbell_row,
        weight: "30–40 kg total",
        sets: "4×6-8", rest: "3 min",
        howto: "Torso inclinado ~30°, agarre supino (palmas arriba). Tira hacia el abdomen bajo retrayendo las escápulas al final. Espalda rígida todo el rato.",
        pro: "El agarre supino (palmas arriba) activa más el dorsal que el agarre prono. Pequeño cambio, gran diferencia.",
      },
      {
        name: "Jalón polea agarre cerrado supino",
        muscle: "Dorsal ancho inferior + bíceps",
        equipment: "Máquina jalón con accesorio en V",
        gif: GIF.lat_pulldown,
        weight: "35–45 kg",
        sets: "3×10-12", rest: "2 min",
        howto: "Agarre cerrado supino (palmas hacia ti). Tira hacia el esternón llevando los codos hacia las caderas. Aprieta omóplatos 1s abajo. Sube sin que los hombros se eleven.",
        pro: "Inclínate ligeramente hacia atrás (~15°) para mejorar la línea de fuerza del jalón.",
      },
      {
        name: "Remo en polea baja sentado",
        muscle: "Romboides + trapecio medio + dorsal",
        equipment: "Cable row — asiento bajo",
        gif: GIF.cable_row,
        weight: "30–40 kg",
        sets: "3×12-15", rest: "90s",
        howto: "Pies en apoyo, rodillas ligeramente flexionadas y fijas. Tira hacia el abdomen, lleva los codos atrás. Retrae las escápulas al final como si quisieras juntarlas. Torso recto.",
        pro: "Pausa 1 segundo con las escápulas retraídas. Esa isometría es donde realmente trabajas los romboides.",
      },
      {
        name: "Curl bíceps con barra EZ",
        muscle: "Bíceps braquial + braquial anterior",
        equipment: "Barra EZ + discos",
        gif: GIF.ez_curl,
        weight: "15–20 kg total",
        sets: "4×8-10", rest: "2 min",
        howto: "De pie, codos pegados al torso. Sube hasta el pecho, contrae 1s. Baja lento 3s hasta casi extensión completa. Sin balanceo del torso ni mover los codos.",
        pro: "La barra EZ reduce el estrés en las muñecas vs barra recta. Más cómodo para la mayoría.",
      },
      {
        name: "Curl martillo con mancuernas",
        muscle: "Braquiorradial + bíceps — cabeza corta",
        equipment: "Mancuernas",
        gif: GIF.hammer_curl,
        weight: "8–10 kg c/mano",
        sets: "3×10-12", rest: "90s",
        howto: "Agarre neutro (pulgar arriba). Sube alternando brazos hasta la altura del hombro. Trabaja el braquiorradial del antebrazo dando grosor total al brazo.",
        pro: "Este agarre activa el braquiorradial que el curl normal ignora. Da el grosor al antebrazo.",
      },
      {
        name: "Face pull en polea",
        muscle: "Deltoides posterior + manguito rotador",
        equipment: "Polea alta con cuerda",
        gif: GIF.face_pull,
        weight: "8–12 kg",
        sets: "3×15", rest: "60s",
        howto: "Polea a la altura de la cara. Tira hacia la cara separando los extremos a los lados de la cabeza (rotación externa). Codos suben y se abren.",
        pro: "Ejercicio OBLIGATORIO. Compensa todo el press y protege el manguito rotador. Nunca lo saltes.",
      },
    ]
  },
  {
    id: "hombros", name: "Hombros", icon: "⚡",
    color: "#ff6b35", label: "PUSH",
    sub: "Deltoides 3 cabezas · Tríceps énfasis",
    exercises: [
      {
        name: "Press Arnold sentado",
        muscle: "Deltoides — las 3 cabezas + tríceps",
        equipment: "Banco con respaldo + mancuernas",
        gif: GIF.arnold_press,
        weight: "8–12 kg c/mano",
        sets: "4×8-10", rest: "2 min",
        howto: "Empieza con palmas mirándote. Al subir, rota las muñecas hacia afuera — al llegar arriba las palmas miran al frente. Baja con la rotación inversa.",
        pro: "La rotación activa las 3 cabezas del deltoides en un solo movimiento. Por eso es superior al press normal.",
      },
      {
        name: "Press con mancuernas sentado",
        muscle: "Deltoides anterior y medial + tríceps",
        equipment: "Banco con respaldo + mancuernas",
        gif: GIF.db_press,
        weight: "10–14 kg c/mano",
        sets: "3×10-12", rest: "2 min",
        howto: "Mancuernas a la altura de los oídos, codos a 90°. Empuja sin bloquear los codos arriba. Baja hasta los 90°. Más seguro para el manguito que la barra.",
        pro: "Mantén la tensión — no bloquees los codos arriba. El músculo trabaja más en tensión constante.",
      },
      {
        name: "Elevaciones laterales en cable",
        muscle: "Deltoides medial",
        equipment: "Polea baja lateral",
        gif: GIF.lat_raise,
        weight: "4–6 kg c/lado",
        sets: "4×15-20", rest: "60s",
        howto: "De lado a la polea baja, agarra con la mano más alejada. Eleva el brazo hasta la altura del hombro. El cable mantiene tensión constante en todo el rango.",
        pro: "El cable da tensión en la posición baja donde las mancuernas no tienen. Úsalos siempre que puedas.",
      },
      {
        name: "Pájaro inclinado (rear delt fly)",
        muscle: "Deltoides posterior + romboides",
        equipment: "Mancuernas — inclinado hacia adelante",
        gif: GIF.rear_fly,
        weight: "4–6 kg c/mano",
        sets: "3×15", rest: "60s",
        howto: "Inclinado hacia adelante ~45°, mancuernas colgando. Codos ligeramente flexionados y fijos. Abre los brazos como alas hasta la altura de los hombros.",
        pro: "El deltoides posterior es el músculo más ignorado del hombro. Trabajarlo da un aspecto completo y 3D.",
      },
      {
        name: "Remo al cuello agarre ancho",
        muscle: "Deltoides medial + trapecios + bíceps",
        equipment: "Barra olímpica",
        gif: GIF.upright_row,
        weight: "20–25 kg total",
        sets: "3×10-12", rest: "90s",
        howto: "Agarre prono ancho (más ancho que los hombros). Tira hacia el cuello llevando los codos hacia los lados (no al techo). Para cuando los codos queden paralelos al suelo.",
        pro: "El agarre ANCHO es clave — reduce el riesgo de pinzamiento del manguito vs agarre estrecho.",
      },
      {
        name: "Press francés tumbado",
        muscle: "Tríceps braquial — cabeza larga (la mayor)",
        equipment: "Banco plano + barra EZ",
        gif: GIF.skullcrusher,
        weight: "15–20 kg EZ total",
        sets: "4×8-10", rest: "2 min",
        howto: "Brazos extendidos hacia el techo, dobla solo los codos llevando la barra hacia la frente. Codos fijos, ni se abren ni se cierran. Baja por encima de la cabeza para mayor estiramiento.",
        pro: "Bajar la barra por encima de la cabeza (no hacia la frente) estira más la cabeza larga del tríceps.",
      },
      {
        name: "Kickback tríceps en cable",
        muscle: "Tríceps — cabeza lateral",
        equipment: "Polea baja con manilla",
        gif: GIF.tri_pushdown,
        weight: "5–8 kg",
        sets: "3×15", rest: "60s",
        howto: "Inclinado hacia adelante, codo fijo al torso y elevado paralelo al suelo. Extiende el antebrazo hasta extensión completa. Mantén 1s apretando.",
        pro: "El cable da tensión constante. Con mancuerna solo hay tensión al principio del movimiento.",
      },
    ]
  },
  {
    id: "espalda_b", name: "Espalda B", icon: "💎",
    color: "#4ecdc4", label: "PULL",
    sub: "Peso muerto · Grosor · Trapecio",
    exercises: [
      {
        name: "Peso muerto convencional",
        muscle: "Toda la cadena posterior: isquios, glúteos, erectores, trapecios",
        equipment: "Barra olímpica en suelo",
        gif: GIF.deadlift,
        weight: "40–55 kg total",
        sets: "4×5", rest: "4 min",
        howto: "Pies a la anchura de caderas, barra sobre el mediopié. Agarre justo fuera de las piernas. Espalda recta, pecho arriba. Empuja el suelo con los pies — no tires de la barra. Cuando pasa las rodillas, empuja la cadera al frente.",
        pro: "Visualiza empujar el suelo hacia atrás con los pies (como si rascalas el suelo). Esto activa los glúteos e isquios automáticamente.",
      },
      {
        name: "Remo a un brazo con mancuerna",
        muscle: "Dorsal ancho + romboides + bíceps — unilateral",
        equipment: "Mancuerna pesada + banco plano",
        gif: GIF.db_row,
        weight: "14–18 kg",
        sets: "4×8-10", rest: "2 min",
        howto: "Rodilla y mano en el banco, espalda paralela al suelo. Tira la mancuerna hacia la cadera (no el pecho), codo pegado al torso. Al llegar arriba, gira ligeramente el torso.",
        pro: "Lleva la mancuerna hacia la cadera, no hacia el pecho. Esto activa más el dorsal.",
      },
      {
        name: "Jalón al pecho agarre ancho prono",
        muscle: "Dorsal ancho superior + redondo mayor",
        equipment: "Máquina jalón con barra larga",
        gif: GIF.lat_pulldown,
        weight: "40–50 kg",
        sets: "3×10-12", rest: "2 min",
        howto: "Agarre prono ancho (20-30cm más que hombros). Tira hacia la clavícula (NUNCA detrás del cuello). Al bajar, lleva los codos hacia las caderas en diagonal.",
        pro: "Detrás del cuello es un mito peligroso. Siempre delante — al pecho o a la clavícula.",
      },
      {
        name: "Encogimientos de trapecios",
        muscle: "Trapecio superior",
        equipment: "Mancuernas pesadas de pie",
        gif: GIF.shrug,
        weight: "18–22 kg c/mano",
        sets: "4×10-12", rest: "90s",
        howto: "Mancuernas a los lados. Sube los hombros directamente hacia las orejas. Mantén 1s arriba. Baja lento. NO hagas rotaciones de hombro — es un mito sin beneficio y con riesgo.",
        pro: "El trapecio aguanta mucha carga. No te quedes corto de peso — es uno de los músculos más fuertes del cuerpo.",
      },
      {
        name: "Curl bíceps concentrado",
        muscle: "Bíceps braquial — pico, cabeza corta",
        equipment: "Mancuerna sentado en banco",
        gif: GIF.conc_curl,
        weight: "8–10 kg",
        sets: "3×12", rest: "90s",
        howto: "Sentado, codo apoyado en la cara interna del muslo. Sube sin mover el codo. Al llegar arriba, rota la muñeca hacia afuera (supinación). Baja muy lento. Aislamiento total.",
        pro: "El apoyo en el muslo elimina completamente el trampa de balancear el torso. Aislamiento puro.",
      },
      {
        name: "Curl bíceps en polea baja",
        muscle: "Bíceps braquial — tensión constante en todo el rango",
        equipment: "Polea baja con barra recta o EZ",
        gif: GIF.ez_curl,
        weight: "10–14 kg",
        sets: "3×15", rest: "60s",
        howto: "Agarre supino, codos fijos al torso. El cable mantiene tensión en todo el rango, incluso arriba donde la mancuerna no tiene.",
        pro: "Combínalo con el curl de mancuernas: la mancuerna trabaja mejor al principio, el cable al final. Son complementarios.",
      },
      {
        name: "Hiperextensiones en banco romano",
        muscle: "Erectores espinales + glúteo mayor + isquiotibiales",
        equipment: "Banco de hiperextensiones",
        gif: GIF.hyperext,
        weight: "Peso corporal → disco 5-10 kg cuando puedas",
        sets: "3×15", rest: "90s",
        howto: "Caderas al borde. Baja el torso hasta ~90° y sube hasta línea recta — no hiperextiendas la columna. Brazos cruzados en el pecho.",
        pro: "Para activar más el glúteo, redondea ligeramente la espalda alta al bajar.",
      },
    ]
  },
  {
    id: "core", name: "Core & Abs", icon: "🔥",
    color: "#ff4757", label: "CORE",
    sub: "Recto abdominal · Core profundo · Oblicuos",
    exercises: [
      {
        name: "Plancha abdominal",
        muscle: "Transverso abdominal + core profundo + glúteos",
        equipment: "Esterilla en el suelo",
        gif: GIF.plank,
        weight: "Peso corporal",
        sets: "4×30-60s", rest: "60s",
        howto: "Apoya codos y punteras. Cuerpo en línea recta de talones a cabeza. Activa el ombligo hacia la columna. Respira profundo. No dejes caer la cadera.",
        pro: "Progresión: 30s → 45s → 60s → 90s. Añadir disco en la espalda para más intensidad.",
      },
      {
        name: "Crunch en polea alta",
        muscle: "Recto abdominal superior e inferior",
        equipment: "Polea alta con cuerda",
        gif: GIF.cable_crunch,
        weight: "10–15 kg",
        sets: "4×12-15", rest: "90s",
        howto: "De rodillas frente a la polea. Cuerda detrás de la cabeza. Flexiona el torso hacia abajo llevando los codos hacia las rodillas. El movimiento es una flexión de columna, no un tirón de brazos.",
        pro: "El único ejercicio abdominal con resistencia progresiva. Úsalo como el press de banca del abdomen.",
      },
      {
        name: "Elevación de piernas colgado",
        muscle: "Recto abdominal inferior + flexores de cadera",
        equipment: "Barra de dominadas",
        gif: GIF.leg_raise,
        weight: "Peso corporal",
        sets: "3×10-15", rest: "90s",
        howto: "Colgado de la barra, espalda pegada. Eleva las piernas hasta los 90° (rodillas dobladas para empezar) o hasta el pecho. Sin balancear el cuerpo.",
        pro: "La bajada controlada es tan importante como la subida. El negativo lento es donde más trabaja el abdominal inferior.",
      },
      {
        name: "Ab wheel (rueda abdominal)",
        muscle: "Core completo: recto, transverso, oblicuos",
        equipment: "Rueda abdominal",
        gif: GIF.ab_wheel,
        weight: "Peso corporal",
        sets: "3×8-10", rest: "2 min",
        howto: "De rodillas, rueda en el suelo frente a ti. Extiende los brazos hacia adelante hasta casi tocar el suelo con el torso. El core aguanta sin que la cadera caiga. Vuelve contrayendo el abdomen.",
        pro: "Empieza con rango parcial. Es un ejercicio difícil. La progresión viene sola con práctica.",
      },
      {
        name: "Russian twist con peso",
        muscle: "Oblicuos + recto abdominal",
        equipment: "Disco o mancuerna",
        gif: GIF.russian,
        weight: "4–6 kg disco",
        sets: "3×20 (10 c/lado)", rest: "75s",
        howto: "Sentado, rodillas ligeramente dobladas, torso inclinado ~45°. Gira el torso llevando el peso de lado a lado. Eleva los pies para más dificultad.",
        pro: "El giro viene de la cintura, no de los brazos. Si sientes los brazos más que el abdomen, estás girando mal.",
      },
      {
        name: "Hollow body hold",
        muscle: "Core profundo + recto abdominal — antiflex. lumbar",
        equipment: "Esterilla",
        gif: GIF.plank,
        weight: "Peso corporal",
        sets: "4×20-30s", rest: "60s",
        howto: "Tumbado boca arriba, presiona la lumbar contra el suelo. Eleva los hombros y las piernas a la vez creando forma de banana invertida. Brazos extendidos arriba.",
        pro: "Si la lumbar se despega del suelo, eleva más las piernas. El contacto lumbar-suelo es el indicador clave.",
      },
      {
        name: "Plank lateral",
        muscle: "Oblicuos + cuadrado lumbar + abductor de cadera",
        equipment: "Esterilla",
        gif: GIF.side_plank,
        weight: "Peso corporal",
        sets: "3×30s c/lado", rest: "60s",
        howto: "Apoya el codo y el lateral del pie. Cadera en línea recta, ni cae ni se eleva. La mano libre en la cadera o extendida arriba.",
        pro: "Es el único ejercicio que aísla bien los oblicuos sin cargar la columna.",
      },
    ]
  },
  {
    id: "futbol", name: "Fútbol", icon: "⚽",
    color: "#00d084", label: "FÚTBOL",
    sub: "Partido 1h · Sin gimnasio este día",
    isFutbol: true,
  },
  {
    id: "descanso", name: "Descanso", icon: "😴",
    color: "#5a5a70", label: "REST",
    sub: "Recuperación activa — movilidad y foam roller",
    isRest: true,
  },
];

// ── COMBO SUGGESTIONS ───────────────────────────────────────────
const COMBOS = [
  { icon: "💪🔥", name: "Pecho + Core",    ids: ["pecho",    "core"] },
  { icon: "🦅🔥", name: "Espalda A + Core", ids: ["espalda",  "core"] },
  { icon: "⚡🔥", name: "Hombros + Core",  ids: ["hombros",  "core"] },
  { icon: "💎🔥", name: "Espalda B + Core", ids: ["espalda_b","core"] },
  { icon: "💪⚡", name: "Pecho + Hombros", ids: ["pecho",    "hombros"] },
  { icon: "🦅💎", name: "Espalda A + B",   ids: ["espalda",  "espalda_b"] },
];

// ── DIET DATA ───────────────────────────────────────────────────
const DIET_DAYS = [
  { name:"Día 1", label:"Push Pecho", meals:[
    { title:"DESAYUNO", time:"07:30", options:[
      { name:"Tortilla de clara + avena", desc:"8 claras + 2 yemas, espinacas. 80g avena + 1 plátano.", prot:52, carbs:65, fat:12, kcal:580 },
      { name:"Salmón + arroz basmati", desc:"200g salmón a la plancha. 120g arroz basmati. Rúcula.", prot:48, carbs:60, fat:18, kcal:590 },
      { name:"Pechuga + batata", desc:"200g pechuga cocida. 150g batata asada. Tomate cherry.", prot:50, carbs:58, fat:5, kcal:480 },
    ]},
    { title:"COMIDA", time:"13:00", options:[
      { name:"Bacalao + quinoa", desc:"250g bacalao al horno con pimientos. 100g quinoa. Brócoli.", prot:58, carbs:52, fat:6, kcal:510 },
      { name:"Ternera magra + arroz", desc:"200g solomillo a la plancha. 120g arroz. Judías verdes.", prot:55, carbs:60, fat:14, kcal:580 },
      { name:"Pechuga + pasta tomate", desc:"200g pechuga marinada. 100g pasta con tomate natural.", prot:52, carbs:72, fat:4, kcal:540 },
    ]},
    { title:"PRE-ENTRENO", time:"16:30", options:[
      { name:"Whey + plátano", desc:"30g whey en agua. 1 plátano. 20g mantequilla de cacahuete.", prot:34, carbs:35, fat:10, kcal:370 },
      { name:"Requesón + avena", desc:"200g requesón 0%. 40g avena. Arándanos.", prot:30, carbs:38, fat:2, kcal:300 },
      { name:"Atún + arroz inflado", desc:"2 latas atún natural. 30g arroz inflado. 1 manzana.", prot:36, carbs:40, fat:3, kcal:330 },
    ]},
    { title:"CENA POST", time:"20:30", options:[
      { name:"Merluza + boniato", desc:"250g merluza al vapor con limón. 120g boniato. Espárragos.", prot:52, carbs:48, fat:4, kcal:440 },
      { name:"Pollo al horno + arroz", desc:"250g pechuga al horno con cúrcuma. 60g arroz. Calabacín.", prot:58, carbs:42, fat:6, kcal:460 },
      { name:"Tortilla claras + atún", desc:"10 claras + 1 yema. 1 lata atún. Tomate y lechuga.", prot:55, carbs:10, fat:8, kcal:340 },
    ]},
  ]},
  { name:"Día 2", label:"Pull Espalda", meals:[
    { title:"DESAYUNO", time:"07:30", options:[
      { name:"Huevos revueltos + tostadas", desc:"3 huevos + 4 claras con champiñones. 2 tostadas centeno.", prot:48, carbs:55, fat:14, kcal:545 },
      { name:"Pavo + avena", desc:"150g pavo cocido. 80g avena con caldo. Tomate.", prot:50, carbs:62, fat:6, kcal:500 },
      { name:"Salmón bowl", desc:"150g salmón ahumado. 100g arroz. Pepino y rúcula.", prot:42, carbs:60, fat:16, kcal:555 },
    ]},
    { title:"COMIDA", time:"13:00", options:[
      { name:"Pechuga rellena + pasta", desc:"250g pechuga rellena espinacas + queso fresco 0%. 100g pasta.", prot:62, carbs:65, fat:8, kcal:585 },
      { name:"Atún rojo + patata", desc:"250g atún rojo a la plancha. 200g patata cocida. Lechuga.", prot:60, carbs:50, fat:10, kcal:545 },
      { name:"Lentejas con pollo", desc:"200g lentejas cocidas. 150g pechuga. Zanahoria y tomate.", prot:55, carbs:68, fat:5, kcal:550 },
    ]},
    { title:"PRE-ENTRENO", time:"16:30", options:[
      { name:"Whey + plátano + nueces", desc:"35g whey. 1 plátano grande. 5 nueces.", prot:38, carbs:38, fat:8, kcal:385 },
      { name:"Skyr + granola", desc:"200g skyr natural. 30g granola sin azúcar. 10 almendras.", prot:28, carbs:34, fat:10, kcal:340 },
      { name:"Tostada pavo + queso", desc:"2 tostadas centeno. 100g pavo. 80g queso fresco 0%.", prot:34, carbs:36, fat:4, kcal:320 },
    ]},
    { title:"CENA POST", time:"20:30", options:[
      { name:"Dorada + quinoa", desc:"250g dorada al horno con limón y hierbas. 80g quinoa.", prot:50, carbs:44, fat:8, kcal:455 },
      { name:"Claras + verduras + arroz", desc:"10 claras. Pisto sin aceite. 70g arroz.", prot:45, carbs:50, fat:3, kcal:410 },
      { name:"Sepia + boniato", desc:"250g sepia a la plancha con ajo y perejil. 120g boniato.", prot:46, carbs:46, fat:5, kcal:420 },
    ]},
  ]},
  { name:"Día 3", label:"Hombros", meals:[
    { title:"DESAYUNO", time:"07:30", options:[
      { name:"Avena proteica + huevos", desc:"100g avena + 30g whey. 4 claras revueltas. 1 kiwi.", prot:54, carbs:75, fat:10, kcal:625 },
      { name:"Tostadas salmón + queso", desc:"3 tostadas centeno. 150g salmón ahumado. 100g queso 0%.", prot:48, carbs:58, fat:14, kcal:570 },
      { name:"Pavo + batata", desc:"200g pavo cocido con especias. 150g batata. Tomate.", prot:50, carbs:56, fat:4, kcal:470 },
    ]},
    { title:"COMIDA", time:"13:00", options:[
      { name:"Lubina + quinoa", desc:"300g lubina al horno. 90g quinoa. Rúcula con vinagre.", prot:58, carbs:48, fat:8, kcal:510 },
      { name:"Ternera wok + arroz", desc:"200g solomillo en tiras. Wok de verduras. 100g arroz.", prot:55, carbs:62, fat:12, kcal:580 },
      { name:"Pasta + atún + tomate", desc:"100g pasta integral. 2 latas atún. Tomate natural con ajo.", prot:50, carbs:72, fat:5, kcal:540 },
    ]},
    { title:"PRE-ENTRENO", time:"16:30", options:[
      { name:"Proteína + fruta", desc:"30g whey en agua. 1 plátano. 1 manzana.", prot:28, carbs:40, fat:2, kcal:295 },
      { name:"Skyr + frutos rojos", desc:"250g skyr. Fresas + arándanos. 1 cucharada de chía.", prot:30, carbs:28, fat:5, kcal:285 },
      { name:"Pan centeno + atún", desc:"2 tostadas centeno. 1 lata atún. Tomate en rodajas.", prot:28, carbs:30, fat:3, kcal:265 },
    ]},
    { title:"CENA POST", time:"20:30", options:[
      { name:"Pulpo + patata", desc:"200g pulpo cocido con pimentón. 120g patata. Pimiento verde.", prot:42, carbs:44, fat:4, kcal:385 },
      { name:"Pollo curry light + arroz", desc:"250g pechuga en curry light (leche coco). 80g arroz.", prot:56, carbs:50, fat:10, kcal:525 },
      { name:"Claras + verdura", desc:"10 claras + 1 yema. Espinacas, champiñones, pimiento.", prot:46, carbs:12, fat:6, kcal:290 },
    ]},
  ]},
  { name:"Día 4", label:"Espalda B", meals:[
    { title:"DESAYUNO", time:"07:30", options:[
      { name:"Salmon bowl proteico", desc:"180g salmón a la plancha. 100g arroz. Espinacas y pepino.", prot:52, carbs:62, fat:16, kcal:605 },
      { name:"Tortilla grande + avena", desc:"3 huevos + 6 claras con queso cottage 0%. 80g avena + plátano.", prot:55, carbs:68, fat:16, kcal:640 },
      { name:"Pavo + arroz + huevo", desc:"150g pavo. 100g arroz. 2 huevos cocidos. Tomate.", prot:52, carbs:60, fat:8, kcal:525 },
    ]},
    { title:"COMIDA", time:"13:00", options:[
      { name:"Pechuga rellena + patata", desc:"250g pechuga rellena de ricotta 0% y espinacas. 150g patata.", prot:64, carbs:52, fat:8, kcal:545 },
      { name:"Gambas + arroz negro", desc:"300g gambas a la plancha con ajo. 100g arroz negro.", prot:52, carbs:58, fat:6, kcal:510 },
      { name:"Solomillo cerdo + boniato", desc:"220g solomillo de cerdo magro a la plancha. 130g boniato.", prot:58, carbs:54, fat:10, kcal:550 },
    ]},
    { title:"PRE-ENTRENO", time:"16:30", options:[
      { name:"Proteína + avena + plátano", desc:"35g whey. 30g avena. 1 plátano. Batido frío.", prot:38, carbs:50, fat:4, kcal:390 },
      { name:"Huevo duro + tostada + fruta", desc:"3 huevos duros (1 yema). 2 tostadas centeno. 1 pera.", prot:30, carbs:36, fat:7, kcal:330 },
      { name:"Requesón + granola + miel", desc:"200g requesón 0%. 25g granola sin azúcar. 10g miel.", prot:28, carbs:32, fat:2, kcal:260 },
    ]},
    { title:"CENA POST", time:"20:30", options:[
      { name:"Bacalao + quinoa", desc:"250g bacalao confitado a baja temperatura. 80g quinoa.", prot:50, carbs:44, fat:8, kcal:460 },
      { name:"Pollo tikka masala light + arroz", desc:"250g pechuga marinada en yogur y especias. 80g arroz.", prot:58, carbs:52, fat:6, kcal:500 },
      { name:"Atún + aguacate + ensalada", desc:"2 latas atún. ½ aguacate. Lechuga, tomate, pepino.", prot:42, carbs:20, fat:16, kcal:400 },
    ]},
  ]},
  { name:"Día 5", label:"Pecho + Core", meals:[
    { title:"DESAYUNO", time:"07:30", options:[
      { name:"Mega avena proteica", desc:"120g avena + 40g whey mezclado. 1 plátano. 15g mantequilla cacahuete.", prot:56, carbs:88, fat:12, kcal:700 },
      { name:"Tortilla 4 huevos + salmón", desc:"4 huevos + 4 claras. 100g salmón ahumado. 2 tostadas centeno.", prot:60, carbs:40, fat:22, kcal:620 },
      { name:"Pollo + arroz + huevo cocido", desc:"200g pechuga cocida. 120g arroz. 2 huevos cocidos.", prot:58, carbs:68, fat:12, kcal:625 },
    ]},
    { title:"COMIDA", time:"13:00", options:[
      { name:"Pechuga + champiñones + pasta", desc:"250g pechuga en salsa de champiñones light. 110g pasta.", prot:64, carbs:72, fat:6, kcal:605 },
      { name:"Rape al horno + arroz", desc:"300g rape al horno con tomate y pimiento. 100g arroz.", prot:58, carbs:60, fat:5, kcal:535 },
      { name:"Judías blancas + pollo", desc:"150g judías cocidas. 200g pechuga. Zanahoria y apio.", prot:62, carbs:62, fat:6, kcal:570 },
    ]},
    { title:"PRE-ENTRENO", time:"16:30", options:[
      { name:"Shake + carbos rápidos", desc:"40g whey. 50g avena. 1 plátano.", prot:44, carbs:60, fat:5, kcal:465 },
      { name:"Yogur + cereal", desc:"300g skyr. 30g copos maíz sin azúcar. Fresas.", prot:34, carbs:38, fat:2, kcal:310 },
      { name:"Sandwich proteico", desc:"2 tostadas centeno. 100g pavo. 1 huevo cocido. Mostaza.", prot:38, carbs:36, fat:6, kcal:355 },
    ]},
    { title:"CENA POST", time:"20:30", options:[
      { name:"Salmón papillote + boniato", desc:"220g salmón con limón y espárragos al papillote. 130g boniato.", prot:50, carbs:52, fat:16, kcal:555 },
      { name:"Pollo limón + arroz + brócoli", desc:"250g pechuga al limón. 80g arroz. Brócoli al vapor.", prot:56, carbs:48, fat:5, kcal:470 },
      { name:"Huevos + atún + verdura", desc:"4 huevos + 1 lata atún. Revuelto con pimientos y cebolla.", prot:48, carbs:18, fat:14, kcal:400 },
    ]},
  ]},
  { name:"Día ⚽", label:"Fútbol", meals:[
    { title:"PRE-PARTIDO", time:"Antes", options:[
      { name:"Avena + huevos (2-3h antes)", desc:"100g avena con leche de avena. 3 huevos revueltos. 1 plátano.", prot:40, carbs:80, fat:14, kcal:620 },
      { name:"Pasta + atún (comida pre-partido)", desc:"120g pasta + 2 latas atún + tomate natural. Pan.", prot:52, carbs:90, fat:5, kcal:620 },
      { name:"Arroz + pollo + plátano", desc:"150g arroz cocido. 200g pechuga. 1 plátano.", prot:50, carbs:85, fat:5, kcal:590 },
    ]},
    { title:"POST-PARTIDO INMEDIATO", time:"30 min después", options:[
      { name:"Whey + 2 plátanos", desc:"40g whey en agua. 2 plátanos. Agua con sales.", prot:40, carbs:65, fat:2, kcal:440 },
      { name:"Arroz + pollo + plátano", desc:"150g arroz. 200g pechuga. 2 plátanos. Agua con sales.", prot:52, carbs:85, fat:5, kcal:600 },
      { name:"Patata + atún + fruta", desc:"200g patata cocida. 2 latas atún. Naranja + manzana.", prot:46, carbs:78, fat:4, kcal:535 },
    ]},
    { title:"CENA (más abundante)", time:"20:30", options:[
      { name:"Salmón + boniato + quinoa", desc:"250g salmón. 150g boniato. 80g quinoa. Verduras.", prot:54, carbs:72, fat:18, kcal:680 },
      { name:"Pollo al horno + pasta", desc:"300g pechuga al horno. 120g pasta con tomate. Ensalada.", prot:68, carbs:75, fat:8, kcal:660 },
      { name:"Huevos + pavo + arroz", desc:"4 huevos + 150g pavo. 100g arroz. Verduras a la plancha.", prot:60, carbs:60, fat:14, kcal:620 },
    ]},
  ]},
  { name:"Día 7", label:"Descanso", meals:[
    { title:"DESAYUNO", time:"08:00", options:[
      { name:"Avena lenta + huevos", desc:"80g avena con leche de almendras. 3 huevos revueltos. Fruta.", prot:38, carbs:60, fat:14, kcal:530 },
      { name:"Pan + aguacate + salmón", desc:"2 tostadas de semillas. ½ aguacate. 100g salmón ahumado.", prot:28, carbs:38, fat:22, kcal:470 },
      { name:"Yogur + granola + nueces", desc:"300g skyr. 30g granola sin azúcar. 20g nueces. 1 plátano.", prot:34, carbs:55, fat:14, kcal:490 },
    ]},
    { title:"COMIDA", time:"13:00", options:[
      { name:"Pollo asado + ensalada", desc:"250g pollo al horno sin piel. Ensalada grande con huevo cocido.", prot:58, carbs:22, fat:10, kcal:420 },
      { name:"Ensalada César proteica", desc:"200g pechuga en tiras. Lechuga romana. Salsa César light.", prot:52, carbs:28, fat:10, kcal:415 },
      { name:"Cocido ligero", desc:"200g pechuga, 100g garbanzos, verduras cocidas. Sin embutido.", prot:55, carbs:52, fat:6, kcal:490 },
    ]},
    { title:"MERIENDA", time:"17:00", options:[
      { name:"Fruta + frutos secos", desc:"1 manzana + 1 pera. 20g nueces. Infusión verde.", prot:6, carbs:48, fat:14, kcal:345 },
      { name:"Requesón + frutos rojos", desc:"200g requesón 0%. Arándanos y fresas. Semillas de lino.", prot:24, carbs:20, fat:2, kcal:200 },
      { name:"Proteína ligera + fruta", desc:"25g whey en agua. 1 fruta de temporada.", prot:24, carbs:20, fat:2, kcal:200 },
    ]},
    { title:"CENA LIGERA", time:"20:00", options:[
      { name:"Crema verduras + huevos", desc:"Crema calabacín + calabaza sin nata. 4 huevos cocidos.", prot:32, carbs:28, fat:10, kcal:335 },
      { name:"Merluza al vapor + ensalada", desc:"200g merluza al vapor. Ensalada verde. Vinagre balsámico.", prot:38, carbs:10, fat:4, kcal:230 },
      { name:"Pavo + verdura a la plancha", desc:"150g pavo. Berenjena + calabacín + pimiento sin aceite.", prot:40, carbs:16, fat:4, kcal:260 },
    ]},
  ]},
];

// ── SUPPLEMENTS ─────────────────────────────────────────────────
const SUPPLEMENTS = [
  { icon:"🥤", name:"Proteína Whey",     dose:"35-40g post-entreno/partido",  desc:"Alta calidad, mínimo 80% proteína por 100g. Post entreno o partido para máxima síntesis proteica." },
  { icon:"⚡", name:"Creatina",           dose:"5g/día — siempre",              desc:"El más estudiado y efectivo. Aumenta fuerza, volumen y recuperación. Beneficia tanto el gym como el fútbol." },
  { icon:"🌊", name:"Omega-3 EPA+DHA",   dose:"2-3g/día con comida",           desc:"Antiinflamatorio. Apoya recuperación muscular y articular. Muy útil para futbolistas por el impacto repetido." },
  { icon:"🍃", name:"Vitamina D3 + K2",  dose:"2000-4000 UI D3 · 100mcg K2",  desc:"Fundamental para la producción de testosterona y absorción de calcio. Deficiencia muy común en España." },
  { icon:"🧲", name:"Magnesio Bisglic.", dose:"300-400mg antes de dormir",     desc:"Mejora el sueño (clave para la recuperación) y reduce calambres musculares. Tomar 30 min antes de acostarte." },
  { icon:"🫀", name:"Zinc",              dose:"15-25mg/día con comida",        desc:"Implicado en producción de testosterona. El sudor genera déficit importante en deportistas." },
];
